### PR TITLE
Removed *.txt files due to Gitignore.

### PR DESCRIPTION
**Pull request by Mikaela**
Also removed users from gitignore, because they match *.txt.

### CODE REVIEW

**Comment by ghost** [comment]
I wonder why doesn't it show my revert of `e4127c1`.

**Comment by Mikaela** [comment]
@nyuszika7h because I didn't revert it. I removed it manually. Eh, did you know that adding to .gitignore doesn't remove already committed files? You must "git rm" them.

**Comment by ghost** [comment]
@Mkaysi I added `users/*.txt` to `.gitignore` file then reverted that commit because `*.txt` ws already there.

**Comment by Mikaela** [comment]
@nyuszika7h Ah, then I know the reason. I didn't merge that commit.

**Comment by Mikaela** [comment]
@nyuszika7h There it is :)

**Comment by ghost** [comment]
Some of this is mine <3

**Pull request merged**
